### Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "Jonathan M",
  "email": "jonathanmwandi6@gmail.com",
  "password": "shal00j1010",
  "phone": "+2547308677002",
  "role": "STUDENT"
}

### verify email
POST http://localhost:3000/auth/verify-email
Content-Type: application/json

{
  "email": "jonathanmwandi6@gmail.com",
  "code":"67579"
}

### request verification code
POST http://localhost:3000/auth/request-verification-code
Content-Type: application/json

{
  "email": "jonathanmwandi@gmail.com"
}

### login 
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "jonathanmulingemwandi@gmail.com",
  "password": "shal00j1010"
}

### login 
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "jonathanmwandi6@gmail.com",
  "password": "shal00j1010"
}

### login 
POST http://localhost:3000/auth/login
Content-Type: application/json

{
 "email": "j26515762@gmail.com",
  "password": "shal00j1010"
}

### login 
POST http://localhost:3000/auth/login
Content-Type: application/json

{
 "email": "j26515762@gmail.com",
  "password": "shal00j1010"
}

### forgot password
POST http://localhost:3000/auth/forgot-password
Content-Type: application/json

{
  "email": "jonathanmulingemwandi@gmail.com"
}


### reset password
POST http://localhost:3000/auth/reset-password
Content-Type: application/json

{
  "email": "jonathanmulingemwandi@gmail.com",
  "code":"88308",
  "password": "shal00j1010"
}


### resend reset code
POST http://localhost:3000/auth/resend-reset-code
Content-Type: application/json

{
  "email": "jonathanmulingemwandi@gmail.com"
}
