### Get Institution Analytics
GET http://localhost:3000/institutions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNGJmYWNhOS03MjkyLTRjNGItOTFhZS00OTBhNGNlMTNiYWYiLCJlbWFpbCI6ImpvbmF0aGFubXdhbmRpNkBnbWFpbC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc3MTExOTU5MCwiZXhwIjoxNzcxMjA1OTkwfQ.xu1fLDTXyR_lFiFwEf72YjHw9bHrJh1eXj19tdtrlBU
