### search
GET http://localhost:3000/search?q=jstar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyYjg0OTlmMS0xODA3LTRhZWItOGEzOS0yNmI1Mzg3MDU5Y2IiLCJlbWFpbCI6ImpvbmF0aGFubXVsaW5nZW13YW5kaUBnbWFpbC5jb20iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc3MjUyMTkzMSwiZXhwIjoxNzcyNjA4MzMxfQ.K_zwkgEVR9FM_INAJD-Vq9rM3fNShlcvZLXYKLOCTPg